import { CssBaseline, GlobalStyles } from "@mui/material";

export const metadata = {
  title: "HOD RAG",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <>
      <CssBaseline />
      <GlobalStyles
        styles={{
          html: { margin: 0 },
          body: { margin: 0 },
        }}
      />
      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  );
}
